-- 진료과
CREATE TABLE DEPARTMENT(
    DEPT_CODE NUMBER PRIMARY KEY, -- 과코드(PK)
    DEPT_NAME VARCHAR2(18) NOT NULL, -- 과이름
    DEPT_LOC VARCHAR2(18) NOT NULL -- 위치
);

-- 환자
CREATE TABLE PATIENT(
    PATIENT_SEQ NUMBER PRIMARY KEY, -- 환자식별번호(PK)
    PATIENT_SSN VARCHAR2(14) UNIQUE NOT NULL, -- 환자주민번호
    PATIENT_ADDRESS VARCHAR2(200) NOT NULL, -- 주소
    PATIENT_NAME VARCHAR2(15) NOT NULL, -- 이름
    PATIENT_PHONE VARCHAR2(13) NOT NULL -- 휴대폰 번호
);

-- 의사
CREATE TABLE DOCTOR(
    DOCTOR_SEQ NUMBER PRIMARY KEY, -- 의사식별번호(PK)
    DOCTOR_SSN VARCHAR2(14) UNIQUE NOT NULL, -- 의사주민번호
    DOCTOR_NAME VARCHAR2(15) NOT NULL, -- 이름
    DEPT_CODE NUMBER CONSTRAINT DOCTOR_DEPT_FK REFERENCES DEPARTMENT (DEPT_CODE) -- 과코드(FK)
);

-- 진료
CREATE TABLE DIAGNOSIS(
    DIAGNOSIS_SEQ NUMBER PRIMARY KEY, -- 진료식별번호 (PK)
    DIAGNOSIS_PRESCRIPTION VARCHAR2(600) NOT NULL, -- 처방
    DIAGNOSIS_DATE DATE NOT NULL, -- 진료일
    PATIENT_SEQ NUMBER CONSTRAINT DIAG_PATIENT_FK REFERENCES PATIENT (PATIENT_SEQ), -- 환자식별번호 (FK)
    DOCTOR_SEQ NUMBER CONSTRAINT DIAG_DOCTOR_FK REFERENCES DOCTOR (DOCTOR_SEQ) -- 의사식별번호 (FK)
);

-- 시간블록
CREATE TABLE TIMEBLOCK(
    TIMEBLOCK_SEQ NUMBER PRIMARY KEY, -- 블록식별번호(PK)
    TIMEBLOCK_TIME DATE NOT NULL -- 시간
);

-- 근무표
CREATE TABLE SCHEDULE(
    SCHEDULE_SEQ NUMBER PRIMARY KEY, -- 근무식별번호(PK)
    DOCTOR_SEQ NUMBER CONSTRAINT SCHE_DOCTOR_FK REFERENCES DOCTOR (DOCTOR_SEQ), -- 의사식별번호(FK)
    START_BLOCK_SEQ NUMBER CONSTRAINT START_BLOCK_FK REFERENCES TIMEBLOCK (TIMEBLOCK_SEQ), -- 근무시작번호(FK)
    END_BLOCK_SEQ NUMBER CONSTRAINT END_BLOCK_FK REFERENCES TIMEBLOCK (TIMEBLOCK_SEQ), -- 근무종료번호(FK)
    SCHEDULE_DATE DATE NOT NULL-- 근무일
);

-- 예약
CREATE TABLE RESERVATION(
    RESERVATION_SEQ NUMBER PRIMARY KEY, -- 예약식별번호(PK)
    RESERVATION_DATE DATE NOT NULL, -- 예약일
    PATIENT_SEQ NUMBER CONSTRAINT RESERV_PATIENT_FK REFERENCES PATIENT (PATIENT_SEQ), -- 환자식별번호(FK)
    SCHEDULE_SEQ NUMBER CONSTRAINT RESERV_SCHEDULE_FK REFERENCES SCHEDULE (SCHEDULE_SEQ), -- 근무식별번호(FK)
    TIMEBLOCK_SEQ NUMBER CONSTRAINT RESERV_TIMEBLOCK_FK REFERENCES TIMEBLOCK (TIMEBLOCK_SEQ) -- 블록식별번호(FK)
);